### ISSUE TITLE
A way to slow down downloading?

### ISSUE THREAD

**Issue by qorl555** [Sean2525/Let-s-panda#10]
Is there a way to add a delay between downloading each image? I got tempbanned for exhentai because they inferred I'm using an auto downloader from "too many pageviews".

**Comment by Sean2525** [comment]
Hi qorl555,

You can edit the userscript on your browser.
Change the "threading" value to slow down the download speed.

https://github.com/Sean2525/Let-s-panda/blob/99d0a37256d57da06212e00565090802bf265a64/src/main.js#L42-L49
