### ISSUE TITLE
Hello, I want to implement the default Viewer page(s): One , not Viewer page(s): All, how should I modify the code?

### ISSUE THREAD

**Issue by zero-tk** [Sean2525/Let-s-panda#12]
Hello, I want to implement the default Viewer page(s): One
, not Viewer page(s): All, how should I modify the code?

**Comment by Sean2525** [comment]
Hi zero-tk,
Do you mean set default viewer mode to "Viewer page(s): One"?

If so, you don't need to modify the code, the script will preserve your option.

I'll close this issue first.
