### ISSUE TITLE
I can't access exhentai 

### ISSUE THREAD

**Issue by darkboy8** [Sean2525/Let-s-panda#2]
I still access i create a new account and wait one month and still see sad panda

**Comment by darkboy8** [comment]
1-chrome
2-tempermonkey
3-no
4-yes but didn't work


And this my account on e-hentai
Name - Darkboy999
Password - 1122334455xxxx
Chick it if it's working

**Comment by darkboy8** [comment]
I create new account how can I know if its enabled

**Comment by Sean2525** [comment]
Just remember to use the private browser, when you want to check.
When you can access successfully, that your account was enabled.

There is no other way to know.
Most people are in 7 days to a month,
But there are also a few people who haven’t enabled for a long time.
