### ISSUE TITLE
Login and download not working anymore

### ISSUE THREAD

**Issue by tomtill** [Sean2525/Let-s-panda#6]
Just recently the login and download feature stopped working. While trying to download all I get is "get href failed". Viewer is still working.

**Comment by Sean2525** [comment]
Hi, thanks for the report, the login bug has been fixed at firefox and chrome,
but that download feature is still working,

Can you give me more information to help me reproduce this error?
e.g. browser information, how to reproduce...

**Comment by tomtill** [comment]
Thanks for the fast response. I updated the script and it seems like the download function is working again for me, ever since you fixed the login page. Thanks! 

If I run into problems again I'll repost back here.
