### ISSUE TITLE
Minor suggestion - swap zoom + and zoom - buttons?

### ISSUE THREAD

**Issue by NintendoManiac64** [Sean2525/Let-s-panda#9]
On a keyboard, the - key is on the left while the + key is on the right.

Also in some programs, like MS Paint, zoom out is on the left while zoom in is on the right (at least it was on Windows 7... for newer OSes I just install Linux instead).

But your script puts zoom in on the left side while zoom out is on the right side.

**Comment by Sean2525** [comment]
Because it doesn't affect the function at all.
If you want to implement the feature, just feel free to PR, swap these lines, and test.

https://github.com/Sean2525/Let-s-panda/blob/99d0a37256d57da06212e00565090802bf265a64/src/main.js#L759-L767

**Comment by NintendoManiac64** [comment]
I also just realized that both Firefox and Chrome have zoom out on the left and zoom in in the right.

As for swapping the parts of the code and testing, I can do that quite easily in the copy of the script saved in my browser and report back at some point - it's actually my inexperience with github that's tripping me up with regards on how the heck one makes a pull request.

**Comment by NintendoManiac64** [comment]
I finally figured out how to make a pull request and have submitted it here:
- https://github.com/Sean2525/Let-s-panda/pull/11

**Comment by NintendoManiac64** [comment]
I'm guessing it'll take a bit of time before the script posted to greasyfork gets this update?

Currently, despite greasyfork saying that the newest version of 0.2.9, actually installing the script installs the previous 0.2.8 version.

**Comment by Sean2525** [comment]
@NintendoManiac64 Yes, it should take some time to update.
